config/routes.rb
Rails.application.routes.draw do
  resources :expenditures
	root :to => "frontpage#index"
	
  resources :frontpage do 
  	get :bank_statment, :on => :collection
  end
  resources :categories
  resources :incomes
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/income.rb
class Income < ApplicationRecord
	has_one :category_mapping, as: :categorizable
	has_one :category, as: :categorizable, through: :category_mapping
	belongs_to :user

	validates :amount, numericality: {greater_than: 0 }, presence: true
	
	accepts_nested_attributes_for :category

	def category_attributes=(category_attributes)
		self.category = Category.find_or_create_by(:name => category_attributes[:name])
	end

end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  before_action :set_income, only: [:show, :edit, :update, :destroy]

  def index
    @expenditures = current_user.incomes.includes(:category)
    respond_to do |format|
      format.html
      format.pdf do
        pdf = WickedPdf.new.pdf_from_string(IncomesController.new.render_to_string(:action => "/report", :layout => false, locals: {income_data: @incomes }))
        send_data(pdf, :filename => "income_report.pdf")
      end
      format.csv do
        send_data(@incomes.as_json, :filename => "income_report.csv")
      end
    end    
  end

  def show
    respond_to do |format|
      format.html
      format.pdf do
        pdf = WickedPdf.new.pdf_from_string(IncomesController.new.render_to_string(:action => "/report", :page_height => '5in', :page_width => '7in', :layout => false, locals: {income: @income, notice: ''}))
        send_data(pdf, :filename => "invoice.pdf", :disposition => 'attachment')
      end
    end
  end

  def new
    @income = Income.new
  end

  def edit
  end

  def create
    @income = Income.new(income_params)

    respond_to do |format|
      if @income.save
        format.html { redirect_to @income, notice: 'Income was successfully created.' }
        format.json { render :show, status: :created, location: @income }
      else
        format.html { render :new }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @income.update(income_params)
        format.html { redirect_to @income, notice: 'Income was successfully updated.' }
        format.json { render :show, status: :ok, location: @income }
      else
        format.html { render :edit }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @income.destroy
    respond_to do |format|
      format.html { redirect_to incomes_url, notice: 'Income was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_income
      @income = Income.find_by(:id=>params[:id], :user_id => current_user.id)
      raise ActiveRecord::RecordNotFound if @income.blank?
    end

    def income_params
      params[:income][:user_id] = current_user.id
      params.require(:income).permit(:amount,:user_id,:category_attributes => [:name])
    end
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/views/incomes/edit.html.erb
<h1>Editing Income</h1>

<%= form_for(@income) do |f| %>
  <div class="field">
    <%= f.label :amount %>
    <%= f.number_field :amount,  min: 1 %>
  </div>

  <%= f.fields_for :category do |fact| %>
    <%= fact.label :name %>
    <%#= select_tag "category", options_from_collection_for_select(@category, 'name','name', @income.category.name)%>
    <%= fact.collection_select "name", Category.all, :name, :name  %>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Show', @income %> |
<%= link_to 'Back', incomes_path %>

app/views/incomes/index.html.erb
<p id="notice"><%= notice %></p>
<h2>Incomes</h2>
<table border=1 class="half_screen">
  <thead>
    <tr>
      <th>Amount</th>
      <th>Category</th>
      <th>Created At</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% if @incomes.present? %> 
      <% @incomes.each do |income| %>
        <tr>
          <td><%= income.amount %></td>
          <td><%= income.category.name %></td>
          <td><%= income.created_at.to_date %></td>
          <td><%= link_to 'Show', income %></td>
          <td><%= link_to 'Edit', edit_income_path(income) %></td>
          <td><%= link_to 'Destroy', income, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <%else%>
      <tr>
        <td colspan="5">No Data Found</td>
      </tr>
    <%end%>
  </tbody>
</table>
<br>
<%= link_to 'New Income', new_income_path %> |
<%= link_to "Download PDF", { :action => "index", :format => :pdf }, target: '_blank'%> |
<%= link_to "Download CSV", { :action => "index", :format => :csv }, target: '_blank'%>

app/views/incomes/new.html.erb
<h1>New Income</h1>

<%= form_for(@income) do |f| %>
	<% if @income.errors.any? %>
		<div id="error_explanation">
		  <h2><%= pluralize(@income.errors.count, "error") %> prohibited this income from being saved:</h2>
		  <ul>
		    <% @income.errors.full_messages.each do |message| %>
		    	<li><%= message %></li>
		    <% end %>
		  </ul>
		</div>
	<% end %>
	<div class="field">
	  <%= f.label :amount %>
	  <%= f.number_field :amount, :required => true,  min: 1  %>
	</div>
	<div id="category">
	  <%= f.fields_for :category, Category.new do |fact| %>
	  <%= fact.label :category %>
	  <%= fact.collection_select "name", Category.all, :name, :name  %>
	  <% end %>
	</div>
	<br>

	<div class="actions">
	  <%= f.submit %>
	</div>
<% end %>
<%= link_to 'Back', incomes_path %>

app/views/incomes/report.html.erb
<h1 style="text-align: center;"><strong>Income Report</strong></h1>
<table style="height: 40px; margin-left: auto; margin-right: auto;" width="100%" border='1'>
	<tbody>
	<tr>
		<th>Amount</th>
		<th>Category</th>
		<th>Created at</th>
	</tr>

	<tbody>
		<% income_data.each do |income| %>
		  <tr>
		    <td style="text-align: center;"><%= income.amount %></td>
		    <td style="text-align: center;"><%= income.category.name %></td>
		    <td style="text-align: center;"><%= income.created_at.to_date %></td>
		  </tr>
		<% end %>
	</tbody>
</table>

app/views/incomes/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Amount:</strong>
  <%= @income.amount %>
</p>
<p>
  <strong>Created:</strong>
  <%= @income.created_at.to_date %>
</p>
<p>
	<strong>Category:</strong>
  <%= @income.category.name %>
</p>

<%= link_to 'Edit', edit_income_path(@income) %> |
<%= link_to 'Back', incomes_path %>