config/routes.rb
Rails.application.routes.draw do
  resources :expenditures
	root :to => "frontpage#index"
	
  resources :frontpage do 
  	get :bank_statment, :on => :collection
  end
  resources :categories
  resources :incomes
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/expenditure.rb
class Expenditure < ApplicationRecord
	has_one :category_mapping, as: :categorizable
	has_one :category, as: :categorizable, through: :category_mapping
	belongs_to :user

	validates :amount, numericality: {greater_than: 0 }, presence: true

	accepts_nested_attributes_for :category

	def category_attributes=(category_attributes)
		self.category = Category.find_or_create_by(:name => category_attributes[:name])
	end
end

app/controllers/expenditures_controller.rb
class ExpendituresController < ApplicationController
  before_action :set_expenditure, only: [:show, :edit, :update, :destroy]

  def index
    @expenditures = current_user.expenditures.includes(:category)
    respond_to do |format|
      format.html
      format.pdf do
        pdf = WickedPdf.new.pdf_from_string(ExpendituresController.new.render_to_string(:action => "/report", :page_height => '5in', :page_width => '7in', :layout => false, locals: {expenditure_data: @expenditures }))
        send_data(pdf, :filename => "expenditure_report.pdf", :disposition => 'attachment')
      end
      format.csv do
        send_data(@expenditures.as_json, :filename => "expenditure_report.csv")
      end
    end
  end

  def show
  end

  def new
    @expenditure = Expenditure.new
  end

  def edit
  end

  def create
    @expenditure = Expenditure.new(expenditure_params)

    respond_to do |format|
      if @expenditure.save
        format.html { redirect_to @expenditure, notice: 'Expenditure was successfully created.' }
        format.json { render :show, status: :created, location: @expenditure }
      else
        format.html { render :new }
        format.json { render json: @expenditure.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @expenditure.update(expenditure_params)
        format.html { redirect_to @expenditure, notice: 'Expenditure was successfully updated.' }
        format.json { render :show, status: :ok, location: @expenditure }
      else
        format.html { render :edit }
        format.json { render json: @expenditure.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @expenditure.destroy
    respond_to do |format|
      format.html { redirect_to expenditures_url, notice: 'Expenditure was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_expenditure
      @expenditure = Expenditure.find_by(:id => params[:id], :user_id => current_user.id)
      raise ActiveRecord::RecordNotFound if @expenditure.blank?
    end

    def expenditure_params
      params[:expenditure][:user_id] = current_user.id
      params.require(:expenditure).permit(:amount,:user_id,:category_attributes => [:name])
    end
end

app/helpers/expenditures_helper.rb
module ExpendituresHelper
end

app/views/expenditures/_form.html.erb
<%= form_for(expenditure) do |f| %>
  <% if expenditure.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(expenditure.errors.count, "error") %> prohibited this expenditure from being saved:</h2>

      <ul>
      <% expenditure.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :amount %>
    <%= f.text_field :amount,  min: 1 %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/expenditures/edit.html.erb
<h1>Editing Expenditure</h1>

<%= render 'form', expenditure: @expenditure %>

<%= link_to 'Show', @expenditure %> |
<%= link_to 'Back', expenditures_path %>

app/views/expenditures/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Expenditures</h2><br>

<table border=1 class="half_screen">
  <thead>
    <tr>
      <th>Amount</th>
      <th>Category</th>
      <th>Created At</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <%if @expenditures.present? %>
      <% @expenditures.each do |expenditure| %>
        <tr>
          <td><%= expenditure.amount %></td>
          <td><%= expenditure.category.name %></td>
          <td><%= expenditure.created_at.to_date %></td>
          <td><%= link_to 'Show', expenditure %></td>
          <td><%= link_to 'Edit', edit_expenditure_path(expenditure) %></td>
          <td><%= link_to 'Destroy', expenditure, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <%else%>
      <tr>
        <td colspan="4">No Data Found</td>
      </tr>
    <%end%>    
  </tbody>
</table>

<br>

<%= link_to 'New Expenditure', new_expenditure_path %> |
<%= link_to "Download PDF", { :action => "index", :format => :pdf }, target: '_blank'%> |
<%= link_to "Download CSV", { :action => "index", :format => :csv }, target: '_blank'%>

app/views/expenditures/new.html.erb
<h1>New Expense</h1>

<%= form_for(@expenditure) do |f| %>
	<% if @expenditure.errors.any? %>
		<div id="error_explanation">
		  <h2><%= pluralize(@expenditure.errors.count, "error") %> prohibited this Expense from being saved:</h2>
		  <ul>
		    <% @expenditure.errors.full_messages.each do |message| %>
		    	<li><%= message %></li>
		    <% end %>
		  </ul>
		</div>
	<% end %>
	<div class="field">
	  <%= f.label :amount %>
	  <%= f.number_field :amount,:required => true %>
	</div>
	<div id="category">
	  <%= f.fields_for :category, Category.new do |fact| %>
	  <%= fact.label :category %>
	  <%= fact.collection_select "name", Category.all, :name, :name  %>
	  <% end %>
	</div>
	<br>

	<div class="actions">
	  <%= f.submit %>
	</div>
<% end %>

<%= link_to 'Back', expenditures_path %>

app/views/expenditures/report.html.erb
<h1 style="text-align: center;"><strong>Expenditure Report</strong></h1>
<table style="height: 40px; margin-left: auto; margin-right: auto;" width="100%" border='1'>
	<tbody>
	<tr>
		<th>Amount</th>
		<th>Category</th>
		<th>Created at</th>
	</tr>

	<tbody>
		<% expenditure_data.each do |expenditure| %>
		  <tr>
		    <td style="text-align: center;"><%= expenditure.amount %></td>
		    <td style="text-align: center;"><%= expenditure.category.name %></td>
		    <td style="text-align: center;"><%= expenditure.created_at.to_date %></td>
		  </tr>
		<% end %>
	</tbody>
</table>

app/views/expenditures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @expenditure.amount %>
</p>

<%= link_to 'Edit', edit_expenditure_path(@expenditure) %> |
<%= link_to 'Back', expenditures_path %>